config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/jual501/apps
      targetRevision: master

applications:
  
  - name: guestbook
  - name: apache
  
  
