config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/argoproj/argocd-example-apps
      targetRevision: master

applications:
  - name: blue-green
    tool:
      helm:
        releaseName: blue-green
  - name: guestbook
  - name: helm-dependency
    tool:
      helm:
        releaseName: helm-dependency
  
